import type { Metadata } from "next";
import { Space_Grotesk } from "next/font/google";
import "./globals.css";

const spaceGrotestFont = Space_Grotesk({
  subsets: ["latin"],
  weight: "variable",
  fallback: ["sans-serif"],
  variable: '--font-space-grotesk',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={spaceGrotestFont.className}>{children}</body>
    </html>
  );
}
